export const ADD_TODO = 'addTodo'
export const REMOVE_TODO = 'removeTodo'
export const COMPLETED_TODO = 'completedTodo'
export const SHOW_ALL_TODO = 'showAllTodo'
export const SHOW_COMPLETED_TODO = 'showCompletedTodo'
export const SHOW_ACTIVE_TODO = 'showActiveTodo'
